### ISSUE TITLE
npm install fails on Node 12

### ISSUE THREAD

**Issue by SeanKilleen** [excellalabs/unanet-summarizer#122]
We currently use node 10.x on both the build server (and I use it on my local).

@jmweir reports that it failed on Node 12 for him.

Since that will be an active LTS soon, I want to ensure things will work appropriately.

As I get the chance, I'll install v12.x via nvm, re-do some of the dependencies, and see if I can get it working there and on the build server.

**Comment by SeanKilleen** [comment]
@jmweir FYI I moved to v12.11.0 and everything worked fine for install and build.

You may want to try removing node_modules and installing / building again.

**Comment by jmweir** [comment]
Issue recurs under node v12.10.0 installed via Homebrew on MacOS. Issue is documented here: https://github.com/nodejs/node/issues/27389

**Comment by jmweir** [comment]
I also confirm that `npm install` works for me without this fix, on both node 10 and 12 installed via `nvm`. That isolates this issue to node 12 from Homebrew. This fix does not break NVM Node 12.

**Comment by SeanKilleen** [comment]
👍👍 sounds good! I'll close this then if you don't think it'll be a concern.

**Comment by jmweir** [comment]
Actually I'd recommend merging that PR :-D
