### ISSUE TITLE
Webpack Dev Server not opening reload socket

### ISSUE THREAD

**Issue by jmweir** [excellalabs/unanet-summarizer#41]
In local debugging mode, the webpack dev server is attempting and failing to open a websocket back to itself. It does this in order to notify the browser whenever source code has changed. This may be a bug in WDS as it is plainly attempting to connect to an incorrect URL.

**Comment by SeanKilleen** [comment]
@jmweir how do you reproduce this? I want to check it out.

**Comment by jmweir** [comment]
Open up Chrome Devtools and observe the errors in the Console. You can also open the Network view and see what connections are failing.

**Comment by SeanKilleen** [comment]
Gotcha. Screenshot here for future reference: 

> ![image](https://user-images.githubusercontent.com/2148318/56866054-3158ce00-69a3-11e9-83fb-9731630d6e0b.png)

**Comment by SeanKilleen** [comment]
Closed via #42.
