### ISSUE TITLE
Incorrect tracking due to being based current day of the month

### ISSUE THREAD

**Issue by SeanKilleen** [excellalabs/unanet-summarizer#47]
I haven't submitted my timesheet yet (shame on me). But when I went to look at the summary to help guide me, I saw: 

![image](https://user-images.githubusercontent.com/2148318/57033417-dc26f180-6c1a-11e9-8184-78017e50a57a.png)

That is...super not correct.

**Comment by SeanKilleen** [comment]
`getDaysLeftInTimesheet` needs to return 0 if the current date is greater than the last date on the timesheet.

**Comment by jmweir** [comment]
We may consider moment.js for handy date math

**Comment by SeanKilleen** [comment]
Resolved by #115.
