### ISSUE TITLE
Bundle size reduction

### ISSUE THREAD

**Issue by SeanKilleen** [excellalabs/unanet-summarizer#676]
The summarizer doesn't do a whole lot. So theoretically, it shouldn't need a whole lot.

But our bundle size is almost 3.5 MB.

I'm no expert in this area, but it seems we can do better than that.

**Comment by agriffi10** [comment]
![Screenshot 2022-10-10 173758](https://user-images.githubusercontent.com/30501888/194956245-a2a90ec5-c308-4a26-8a1c-8a14c6c29ae2.png)

**Comment by agriffi10** [comment]
Moment.js is definitely a culprit here, and if I remember correctly, it's deprecated.
